"""Prepare Phase 2 interim tables from raw sources.

This script intentionally uses only the Python standard library. It reads:

- IBGE Census 2022 GeoPackage attributes through sqlite3.
- SGB/CPRM susceptibility Shapefiles directly from the raw ZIP.
- Data.Rio neighborhood boundaries for projected-coordinate assignment.

Outputs are cleaned interim tables under data/interim/. Final app-ready
GeoJSON and score bundles are generated by build_phase2_outputs.mjs.
"""

from __future__ import annotations

import csv
import json
import math
import re
import sqlite3
import struct
import unicodedata
import zipfile
from collections import defaultdict
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable


PROJECT_ROOT = Path(__file__).resolve().parents[2]
INTERIM_DIR = PROJECT_ROOT / "data" / "interim"

IBGE_GPKG = (
    PROJECT_ROOT
    / "data"
    / "raw"
    / "ibge"
    / "ibge__setores_censitarios_agregados_rj__2022"
    / "RJ_setores_CD2022_agregados.gpkg"
)

BAIRROS_JSON = (
    PROJECT_ROOT
    / "data"
    / "raw"
    / "data-rio"
    / "data-rio__limites_bairros__atual"
    / "limites_bairros.json"
)

SGB_SIG_ZIP = (
    PROJECT_ROOT
    / "data"
    / "raw"
    / "sgb-cprm"
    / "sgb-cprm__rio_suscetibilidade_sig_zip__2018"
    / "sig_riodejaneiro_rj_suscet.zip"
)

RIO_MUNICIPALITY_CODE = "3304557"

NEIGHBORHOOD_NAME_ALIASES = {
    "freguesia (ilha do governador)": "freguesia (ilha)",
    "oswaldo cruz": "osvaldo cruz",
    "sao cristovao": "imperial de sao cristovao"
}

SGB_LAYER_FILES = {
    "inundacao": "Suscetibilidade/Inundacao_A",
    "enxurrada": "Suscetibilidade/Enxurrada_A",
    "movimento_massa": "Suscetibilidade/Movimento_de_Massa_A",
    "corrida_massa": "Suscetibilidade/Corrida_de_massa_A"
}

SGB_CLASS_WEIGHTS = {
    "baixa": 1.0,
    "media": 2.0,
    "média": 2.0,
    "alta": 3.0,
    "suscetivel": 2.0,
    "suscetível": 2.0
}


@dataclass
class NeighborhoodBoundary:
    key: str
    code: str
    name: str
    planning_area: str
    area_m2: float
    rings: list[list[tuple[float, float]]]


@dataclass
class ShpPolygon:
    parts: list[list[tuple[float, float]]]
    bbox: tuple[float, float, float, float]


def main() -> None:
    INTERIM_DIR.mkdir(parents=True, exist_ok=True)

    boundaries = read_neighborhood_boundaries()
    ibge_report = prepare_ibge_by_neighborhood(boundaries)
    sgb_report = prepare_sgb_susceptibility(boundaries)

    write_json(
        INTERIM_DIR / "phase2_interim_manifest.json",
        {
            "generatedAt": now_iso(),
            "outputs": [
                "data/interim/ibge_census2022_basic_by_neighborhood.csv",
                "data/interim/ibge_census2022_city_summary.json",
                "data/interim/sgb_susceptibility_by_neighborhood.csv",
                "data/interim/sgb_susceptibility_quality.json"
            ],
            "ibge": ibge_report,
            "sgb_cprm": sgb_report
        }
    )

    print("Wrote Phase 2 interim source tables.")


def prepare_ibge_by_neighborhood(
    boundaries: dict[str, NeighborhoodBoundary]
) -> dict[str, Any]:
    rows_by_key: dict[str, dict[str, Any]] = {}
    unknown_names: dict[str, dict[str, Any]] = {}

    for key, boundary in boundaries.items():
        rows_by_key[key] = {
            "neighborhood_key": key,
            "neighborhood_code": boundary.code,
            "neighborhood_name": boundary.name,
            "planning_area": boundary.planning_area,
            "source_neighborhood_names": set(),
            "sector_count": 0,
            "official_area_km2": boundary.area_m2 / 1_000_000,
            "ibge_sector_area_km2": 0.0,
            "v0001_population_total": 0.0,
            "v0002_private_households": 0.0,
            "v0003_permanent_private_households": 0.0,
            "v0004_collective_households_with_residents": 0.0,
            "v0005_weighted_sum": 0.0,
            "v0006_weighted_sum": 0.0,
            "v0007_occupied_private_households": 0.0,
            "v0005_weight": 0.0,
            "v0006_weight": 0.0
        }

    con = sqlite3.connect(IBGE_GPKG)
    cur = con.cursor()
    query = """
        select
            NM_BAIRRO,
            AREA_KM2,
            v0001,
            v0002,
            v0003,
            v0004,
            v0005,
            v0006,
            v0007
        from RJ_setores_CD2022
        where CD_MUN = ?
    """

    for row in cur.execute(query, (RIO_MUNICIPALITY_CODE,)):
        (
            source_name,
            area_km2,
            v0001,
            v0002,
            v0003,
            v0004,
            v0005,
            v0006,
            v0007
        ) = row

        source_key = normalize_name(source_name)
        key = NEIGHBORHOOD_NAME_ALIASES.get(source_key, source_key)

        target = rows_by_key.get(key)
        if target is None:
            target = unknown_names.setdefault(
                source_key,
                {
                    "source_neighborhood_name": source_name,
                    "sector_count": 0,
                    "v0001_population_total": 0.0,
                    "ibge_sector_area_km2": 0.0
                }
            )
            target["sector_count"] += 1
            target["v0001_population_total"] += to_float(v0001)
            target["ibge_sector_area_km2"] += to_float(area_km2)
            continue

        target["source_neighborhood_names"].add(str(source_name or "").strip())
        target["sector_count"] += 1
        target["ibge_sector_area_km2"] += to_float(area_km2)
        target["v0001_population_total"] += to_float(v0001)
        target["v0002_private_households"] += to_float(v0002)
        target["v0003_permanent_private_households"] += to_float(v0003)
        target["v0004_collective_households_with_residents"] += to_float(v0004)
        target["v0007_occupied_private_households"] += to_float(v0007)

        v0007_weight = to_float(v0007)
        if v0005 is not None and v0007_weight > 0:
            target["v0005_weighted_sum"] += to_float(v0005) * v0007_weight
            target["v0005_weight"] += v0007_weight
        if v0006 is not None and v0007_weight > 0:
            target["v0006_weighted_sum"] += to_float(v0006) * v0007_weight
            target["v0006_weight"] += v0007_weight

    con.close()

    output_rows = []
    for key in sorted(rows_by_key):
        row = rows_by_key[key]
        has_census_match = row["sector_count"] > 0
        population = row["v0001_population_total"]
        area = row["official_area_km2"]
        occupied_households = row["v0007_occupied_private_households"]
        row_out = {
            "neighborhood_key": row["neighborhood_key"],
            "neighborhood_code": row["neighborhood_code"],
            "neighborhood_name": row["neighborhood_name"],
            "planning_area": row["planning_area"],
            "source_neighborhood_names": "; ".join(
                sorted(name for name in row["source_neighborhood_names"] if name)
            ),
            "sector_count": row["sector_count"],
            "official_area_km2": round_float(area),
            "ibge_sector_area_km2": round_float(row["ibge_sector_area_km2"]) if has_census_match else None,
            "v0001_population_total": round_int(population) if has_census_match else None,
            "v0002_private_households": round_int(row["v0002_private_households"]) if has_census_match else None,
            "v0003_permanent_private_households": round_int(
                row["v0003_permanent_private_households"]
            ) if has_census_match else None,
            "v0004_collective_households_with_residents": round_int(
                row["v0004_collective_households_with_residents"]
            ) if has_census_match else None,
            "v0007_occupied_private_households": round_int(occupied_households) if has_census_match else None,
            "v0005_avg_residents_private_households_weighted": round_float(
                safe_div(row["v0005_weighted_sum"], row["v0005_weight"])
            ) if has_census_match else None,
            "v0006_avg_imputation_or_quality_flag_weighted": round_float(
                safe_div(row["v0006_weighted_sum"], row["v0006_weight"])
            ) if has_census_match else None,
            "population_density_per_km2": round_float(safe_div(population, area)) if has_census_match else None,
            "occupied_household_density_per_km2": round_float(
                safe_div(occupied_households, area)
            ) if has_census_match else None
        }
        output_rows.append(row_out)

    write_csv(
        INTERIM_DIR / "ibge_census2022_basic_by_neighborhood.csv",
        output_rows
    )

    total_population = sum(row["v0001_population_total"] or 0 for row in output_rows)
    total_area = sum(row["official_area_km2"] for row in output_rows)
    missing_official = [
        row["neighborhood_name"]
        for row in output_rows
        if row["sector_count"] == 0
    ]

    report = {
        "source": rel_path(IBGE_GPKG),
        "rioMunicipalityCode": RIO_MUNICIPALITY_CODE,
        "neighborhoodRows": len(output_rows),
        "matchedNeighborhoodRows": len(output_rows) - len(missing_official),
        "officialNeighborhoodsWithoutCensusNameMatch": missing_official,
        "unmatchedCensusNeighborhoodNames": sorted(unknown_names.values(), key=lambda item: item["source_neighborhood_name"]),
        "populationTotalMatched": round_int(total_population),
        "officialAreaKm2": round_float(total_area),
        "notes": [
            "Census sectors are aggregated by IBGE NM_BAIRRO after conservative name normalization.",
            "Freguesia (Ilha do Governador), Oswaldo Cruz, and Sao Cristovao are harmonized to municipal names used by Data.Rio.",
            "Neighborhoods with no Census 2022 name match are kept with null census metrics rather than imputed."
        ]
    }

    write_json(INTERIM_DIR / "ibge_census2022_city_summary.json", report)
    return report


def prepare_sgb_susceptibility(
    boundaries: dict[str, NeighborhoodBoundary]
) -> dict[str, Any]:
    aggregates: dict[str, dict[str, Any]] = {}
    for key, boundary in boundaries.items():
        aggregates[key] = {
            "neighborhood_key": key,
            "neighborhood_code": boundary.code,
            "neighborhood_name": boundary.name,
            "planning_area": boundary.planning_area,
            "official_area_km2": boundary.area_m2 / 1_000_000,
            "feature_count": 0,
            "inundacao_feature_count": 0,
            "inundacao_low_area_km2": 0.0,
            "inundacao_medium_area_km2": 0.0,
            "inundacao_high_area_km2": 0.0,
            "inundacao_weighted_area": 0.0,
            "enxurrada_area_km2": 0.0,
            "movimento_massa_weighted_area": 0.0,
            "corrida_massa_area_km2": 0.0
        }

    unassigned: dict[str, dict[str, Any]] = defaultdict(
        lambda: {"feature_count": 0, "area_km2": 0.0}
    )
    source_counts: dict[str, int] = {}

    with zipfile.ZipFile(SGB_SIG_ZIP) as zf:
        for layer_id, base_name in SGB_LAYER_FILES.items():
            shp_name = find_zip_member(zf, f"{base_name}.shp")
            dbf_name = find_zip_member(zf, f"{base_name}.dbf")
            cpg_name = find_zip_member(zf, f"{base_name}.cpg", required=False)
            prj_name = find_zip_member(zf, f"{base_name}.prj", required=False)

            encoding = dbf_encoding(zf.read(cpg_name).decode("ascii", "ignore")) if cpg_name else "cp1252"
            records = read_dbf_records(zf.read(dbf_name), encoding)
            shapes = read_shp_polygons(zf.read(shp_name))
            prj_text = zf.read(prj_name).decode("utf-8", "replace") if prj_name else ""

            if len(records) != len(shapes):
                raise ValueError(
                    f"SGB layer {layer_id} has {len(records)} DBF rows and {len(shapes)} geometries"
                )

            source_counts[layer_id] = len(shapes)

            for attrs, shape in zip(records, shapes):
                centroid = polygon_centroid(shape.parts)
                if centroid is None:
                    continue
                target_key = find_containing_neighborhood(centroid, boundaries)
                area_km2 = polygon_area_m2(shape.parts) / 1_000_000
                class_name = str(attrs.get("CLASSE") or "").strip()
                class_key = normalize_name(class_name)
                class_weight = SGB_CLASS_WEIGHTS.get(class_key, 1.0)

                if target_key is None:
                    unassigned[layer_id]["feature_count"] += 1
                    unassigned[layer_id]["area_km2"] += area_km2
                    continue

                target = aggregates[target_key]
                target["feature_count"] += 1

                if layer_id == "inundacao":
                    target["inundacao_feature_count"] += 1
                    if class_weight >= 3:
                        target["inundacao_high_area_km2"] += area_km2
                    elif class_weight >= 2:
                        target["inundacao_medium_area_km2"] += area_km2
                    else:
                        target["inundacao_low_area_km2"] += area_km2
                    target["inundacao_weighted_area"] += area_km2 * class_weight
                elif layer_id == "enxurrada":
                    target["enxurrada_area_km2"] += area_km2
                elif layer_id == "movimento_massa":
                    target["movimento_massa_weighted_area"] += area_km2 * class_weight
                elif layer_id == "corrida_massa":
                    target["corrida_massa_area_km2"] += area_km2

            if "SIRGAS_2000_UTM_Zone_23S" not in prj_text:
                raise ValueError(
                    f"Unexpected SGB CRS for {layer_id}: {prj_text[:120]}"
                )

    output_rows = []
    for key in sorted(aggregates):
        row = aggregates[key]
        area = row["official_area_km2"]
        inund_total = (
            row["inundacao_low_area_km2"]
            + row["inundacao_medium_area_km2"]
            + row["inundacao_high_area_km2"]
        )
        row_out = {
            "neighborhood_key": row["neighborhood_key"],
            "neighborhood_code": row["neighborhood_code"],
            "neighborhood_name": row["neighborhood_name"],
            "planning_area": row["planning_area"],
            "official_area_km2": round_float(area),
            "feature_count": row["feature_count"],
            "inundacao_feature_count": row["inundacao_feature_count"],
            "inundacao_low_area_km2": round_float(row["inundacao_low_area_km2"]),
            "inundacao_medium_area_km2": round_float(row["inundacao_medium_area_km2"]),
            "inundacao_high_area_km2": round_float(row["inundacao_high_area_km2"]),
            "inundacao_total_area_km2": round_float(inund_total),
            "inundacao_area_share_of_neighborhood": round_float(
                safe_div(inund_total, area)
            ),
            "inundacao_high_area_share_of_neighborhood": round_float(
                safe_div(row["inundacao_high_area_km2"], area)
            ),
            "inundacao_weighted_area_index": round_float(
                safe_div(row["inundacao_weighted_area"], area)
            ),
            "enxurrada_area_km2": round_float(row["enxurrada_area_km2"]),
            "enxurrada_area_share_of_neighborhood": round_float(
                safe_div(row["enxurrada_area_km2"], area)
            ),
            "movimento_massa_weighted_area_index": round_float(
                safe_div(row["movimento_massa_weighted_area"], area)
            ),
            "corrida_massa_area_share_of_neighborhood": round_float(
                safe_div(row["corrida_massa_area_km2"], area)
            )
        }
        output_rows.append(row_out)

    write_csv(
        INTERIM_DIR / "sgb_susceptibility_by_neighborhood.csv",
        output_rows
    )

    report = {
        "source": rel_path(SGB_SIG_ZIP),
        "layersRead": source_counts,
        "assignmentMethod": "Polygon centroid allocated to official Data.Rio neighborhood boundaries in SIRGAS 2000 UTM 23S.",
        "classWeights": SGB_CLASS_WEIGHTS,
        "unassigned": {
            layer: {
                "feature_count": values["feature_count"],
                "area_km2": round_float(values["area_km2"])
            }
            for layer, values in sorted(unassigned.items())
        },
        "limitations": [
            "Centroid allocation is a screening approximation and can misallocate polygons crossing neighborhood borders.",
            "SGB susceptibility classes are hazard context; they do not represent event probability or current drainage condition.",
            "The first score uses inundation evidence directly and treats mass-movement/flash-flood layers as supporting context."
        ]
    }
    write_json(INTERIM_DIR / "sgb_susceptibility_quality.json", report)
    return report


def read_neighborhood_boundaries() -> dict[str, NeighborhoodBoundary]:
    data = json.loads(BAIRROS_JSON.read_text(encoding="utf-8"))
    boundaries: dict[str, NeighborhoodBoundary] = {}
    for feature in data["features"]:
        attrs = feature["attributes"]
        name = str(attrs["nome"]).strip()
        code = str(attrs["codbnum"])
        key = normalize_name(name)
        rings = [
            [(float(x), float(y)) for x, y in ring]
            for ring in feature["geometry"]["rings"]
        ]
        boundaries[key] = NeighborhoodBoundary(
            key=key,
            code=code,
            name=name,
            planning_area=f"AP{attrs['area_plane']}",
            area_m2=to_float(attrs.get("Shape__Area")),
            rings=rings
        )
    return boundaries


def read_shp_polygons(data: bytes) -> list[ShpPolygon]:
    if data[:4] != b"\x00\x00'\x0a":
        raise ValueError("Not an ESRI Shapefile")

    shapes: list[ShpPolygon] = []
    offset = 100
    while offset + 8 <= len(data):
        _record_number, content_length_words = struct.unpack(">2i", data[offset:offset + 8])
        offset += 8
        content_length = content_length_words * 2
        content = data[offset:offset + content_length]
        offset += content_length

        if len(content) < 4:
            continue
        shape_type = struct.unpack("<i", content[:4])[0]
        if shape_type == 0:
            continue
        if shape_type not in (5, 15):
            raise ValueError(f"Unsupported Shapefile shape type: {shape_type}")

        bbox = struct.unpack("<4d", content[4:36])
        num_parts, num_points = struct.unpack("<2i", content[36:44])
        parts_offset = 44
        parts = list(
            struct.unpack(
                f"<{num_parts}i",
                content[parts_offset:parts_offset + (num_parts * 4)]
            )
        )
        points_offset = parts_offset + (num_parts * 4)
        points = [
            struct.unpack("<2d", content[points_offset + i * 16:points_offset + (i + 1) * 16])
            for i in range(num_points)
        ]
        polygon_parts: list[list[tuple[float, float]]] = []
        for index, start in enumerate(parts):
            end = parts[index + 1] if index + 1 < len(parts) else len(points)
            polygon_parts.append([(float(x), float(y)) for x, y in points[start:end]])

        shapes.append(ShpPolygon(parts=polygon_parts, bbox=bbox))

    return shapes


def read_dbf_records(data: bytes, encoding: str) -> list[dict[str, Any]]:
    num_records = struct.unpack("<I", data[4:8])[0]
    header_len = struct.unpack("<H", data[8:10])[0]
    record_len = struct.unpack("<H", data[10:12])[0]

    fields = []
    position = 32
    while position < header_len and data[position] != 0x0D:
        raw = data[position:position + 32]
        name = raw[:11].split(b"\x00", 1)[0].decode("ascii", "ignore")
        field_type = chr(raw[11])
        length = raw[16]
        decimals = raw[17]
        fields.append((name, field_type, length, decimals))
        position += 32

    records: list[dict[str, Any]] = []
    for record_index in range(num_records):
        start = header_len + record_index * record_len
        record = data[start:start + record_len]
        if not record or record[0:1] == b"*":
            continue

        offset = 1
        values: dict[str, Any] = {}
        for name, field_type, length, _decimals in fields:
            raw_value = record[offset:offset + length]
            offset += length
            text = raw_value.decode(encoding, "replace").strip()
            if text == "":
                values[name] = None
            elif field_type in {"N", "F"}:
                values[name] = to_float(text)
            else:
                values[name] = text
        records.append(values)

    return records


def find_zip_member(
    zf: zipfile.ZipFile,
    expected_name: str,
    *,
    required: bool = True
) -> str | None:
    expected = expected_name.lower()
    for info in zf.infolist():
        if info.filename.lower() == expected:
            return info.filename
    if required:
        raise FileNotFoundError(expected_name)
    return None


def dbf_encoding(cpg_text: str) -> str:
    value = cpg_text.strip().lower()
    if "utf" in value:
        return "utf-8"
    if "1252" in value or "ansi" in value:
        return "cp1252"
    return "cp1252"


def polygon_area_m2(parts: Iterable[list[tuple[float, float]]]) -> float:
    signed = sum(ring_signed_area(part) for part in parts if len(part) >= 3)
    return abs(signed)


def polygon_centroid(parts: Iterable[list[tuple[float, float]]]) -> tuple[float, float] | None:
    largest_part: list[tuple[float, float]] | None = None
    largest_area = 0.0
    for part in parts:
        area = abs(ring_signed_area(part))
        if area > largest_area:
            largest_area = area
            largest_part = part

    if not largest_part:
        return None

    centroid = ring_centroid(largest_part)
    if centroid is not None:
        return centroid

    x_values = [point[0] for point in largest_part]
    y_values = [point[1] for point in largest_part]
    return (sum(x_values) / len(x_values), sum(y_values) / len(y_values))


def ring_signed_area(ring: list[tuple[float, float]]) -> float:
    if len(ring) < 3:
        return 0.0
    area = 0.0
    for index, (x1, y1) in enumerate(ring):
        x2, y2 = ring[(index + 1) % len(ring)]
        area += x1 * y2 - x2 * y1
    return area / 2


def ring_centroid(ring: list[tuple[float, float]]) -> tuple[float, float] | None:
    area_factor = 0.0
    x_sum = 0.0
    y_sum = 0.0
    for index, (x1, y1) in enumerate(ring):
        x2, y2 = ring[(index + 1) % len(ring)]
        cross = x1 * y2 - x2 * y1
        area_factor += cross
        x_sum += (x1 + x2) * cross
        y_sum += (y1 + y2) * cross

    if abs(area_factor) < 1e-9:
        return None
    return (x_sum / (3 * area_factor), y_sum / (3 * area_factor))


def find_containing_neighborhood(
    point: tuple[float, float],
    boundaries: dict[str, NeighborhoodBoundary]
) -> str | None:
    for key, boundary in boundaries.items():
        if point_in_rings(point, boundary.rings):
            return key
    return None


def point_in_rings(point: tuple[float, float], rings: list[list[tuple[float, float]]]) -> bool:
    inside = False
    for ring in rings:
        if point_in_ring(point, ring):
            inside = not inside
    return inside


def point_in_ring(point: tuple[float, float], ring: list[tuple[float, float]]) -> bool:
    x, y = point
    inside = False
    if len(ring) < 3:
        return False

    j = len(ring) - 1
    for i in range(len(ring)):
        xi, yi = ring[i]
        xj, yj = ring[j]
        intersects = ((yi > y) != (yj > y)) and (
            x < (xj - xi) * (y - yi) / ((yj - yi) or 1e-12) + xi
        )
        if intersects:
            inside = not inside
        j = i
    return inside


def normalize_name(value: Any) -> str:
    text = str(value or "").strip().lower().replace("\xa0", " ")
    text = unicodedata.normalize("NFKD", text)
    text = "".join(char for char in text if not unicodedata.combining(char))
    text = re.sub(r"\s+", " ", text)
    return text


def write_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    if not rows:
        raise ValueError(f"No rows to write for {path}")
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)


def write_json(path: Path, payload: Any) -> None:
    path.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8"
    )


def safe_div(numerator: Any, denominator: Any) -> float | None:
    num = to_float(numerator)
    den = to_float(denominator)
    if den == 0:
        return None
    return num / den


def to_float(value: Any) -> float:
    if value is None:
        return 0.0
    if isinstance(value, (int, float)):
        if math.isnan(value):
            return 0.0
        return float(value)
    text = str(value).strip().replace(",", ".")
    if text == "":
        return 0.0
    try:
        return float(text)
    except ValueError:
        return 0.0


def round_float(value: Any, digits: int = 6) -> float | None:
    if value is None:
        return None
    number = to_float(value)
    return round(number, digits)


def round_int(value: Any) -> int:
    return int(round(to_float(value)))


def rel_path(path: Path) -> str:
    return path.relative_to(PROJECT_ROOT).as_posix()


def now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


if __name__ == "__main__":
    main()
